import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    // Common
    'common.voltura': 'Voltura',
    'common.slogan': 'See the Savings',
    'common.login': 'Masuk',
    'common.signup': 'Daftar',
    'common.logout': 'Keluar',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.continue': 'Lanjutkan',
    
    // Login
    'login.title': 'Selamat Datang Kembali',
    'login.subtitle': 'Masuk ke akun Anda untuk melanjutkan',
    'login.email': 'Email',
    'login.password': 'Kata Sandi',
    'login.forgot': 'Lupa kata sandi?',
    'login.button': 'Masuk',
    'login.noAccount': 'Belum punya akun?',
    'login.signupLink': 'Daftar Sekarang',
    'login.hero.title': 'Kelola Energi,\\nSelamatkan Bumi',
    'login.hero.subtitle': 'Platform manajemen energi cerdas untuk bisnis berkelanjutan di Indonesia',
    'login.feature1.title': 'Hemat hingga 30%',
    'login.feature1.desc': 'Kurangi biaya listrik dengan rekomendasi berbasis AI',
    'login.feature2.title': 'Monitoring Real-time',
    'login.feature2.desc': 'Pantau konsumsi energi secara langsung dan akurat',
    'login.feature3.title': 'Dampak Lingkungan',
    'login.feature3.desc': 'Lacak kontribusi Anda terhadap pengurangan emisi karbon',
    'login.error.fill': 'Silakan isi semua field',
    'login.error.email': 'Format email tidak valid',
    'login.placeholder.email': 'nama@perusahaan.com',
    'login.placeholder.password': 'Masukkan kata sandi',
    'login.footer': '© 2025 Voltura - Platform Energi Berkelanjutan Indonesia',
    
    // Signup
    'signup.title': 'Buat Akun Baru',
    'signup.subtitle': 'Daftar untuk mulai mengoptimalkan energi Anda',
    'signup.name': 'Nama Lengkap',
    'signup.email': 'Email',
    'signup.company': 'Nama Perusahaan',
    'signup.phone': 'Nomor Telepon',
    'signup.password': 'Kata Sandi',
    'signup.confirmPassword': 'Konfirmasi Kata Sandi',
    'signup.button': 'Buat Akun',
    'signup.loading': 'Membuat akun...',
    'signup.hasAccount': 'Sudah punya akun?',
    'signup.loginLink': 'Masuk',
    'signup.hero.title': 'Kelola Energi,\\nSelamatkan Bumi',
    'signup.hero.subtitle': 'Bergabunglah dengan ribuan bisnis yang telah menghemat hingga 30% biaya energi',
    'signup.benefit1.title': 'Hemat Biaya Listrik',
    'signup.benefit1.desc': 'Identifikasi pemborosan energi dan dapatkan rekomendasi yang dapat menghemat hingga 30%',
    'signup.benefit2.title': 'Real-time Monitoring',
    'signup.benefit2.desc': 'Pantau konsumsi energi langsung dari dashboard yang mudah dipahami',
    'signup.benefit3.title': 'Setup Cepat',
    'signup.benefit3.desc': 'Mulai dalam hitungan menit dengan wizard setup yang dipandu',
    'signup.stats.users': 'Pengguna Aktif',
    'signup.stats.savings': 'Penghematan Rata-rata',
    'signup.stats.co2': 'CO₂ Dikurangi',
    'signup.error.fill': 'Silakan isi semua field',
    'signup.error.email': 'Format email tidak valid',
    'signup.error.password': 'Kata sandi minimal 6 karakter',
    'signup.error.match': 'Kata sandi tidak cocok',
    'signup.placeholder.name': 'Budi Santoso',
    'signup.placeholder.email': 'nama@perusahaan.com',
    'signup.placeholder.company': 'PT. Contoh Indonesia',
    'signup.placeholder.phone': '08123456789',
    'signup.placeholder.password': 'Minimal 6 karakter',
    'signup.placeholder.confirmPassword': 'Ulangi kata sandi',
    
    // Toast notifications
    'toast.welcome': 'Selamat datang {{name}}!',
    'toast.accountCreated': 'Akun Anda telah berhasil dibuat.',
    'toast.emailExists': 'Email sudah terdaftar',
    'toast.emailExistsDesc': 'Email ini sudah digunakan. Coba login atau gunakan email lain.',
    'toast.goToLogin': 'Ke Halaman Login',
    'toast.signupFailed': 'Pendaftaran Gagal',
    'toast.connectionError': 'Kesalahan Koneksi',
    'toast.networkError': 'Kesalahan jaringan. Silakan periksa koneksi Anda dan coba lagi.',
    'toast.welcomeBack': 'Selamat datang kembali!',
    'toast.loggedInAs': 'Masuk sebagai {{name}}',
    'toast.loginFailed': 'Login Gagal',
    'toast.dataSaved': 'Data Berhasil Disimpan',
    'toast.dataSavedDesc': 'Setup listrik Anda telah tersimpan',
    'toast.dataSaveWarning': 'Setup selesai tapi tidak tersimpan',
    'toast.dataSaveWarningDesc': 'Anda tetap bisa melanjutkan menggunakan aplikasi',
    'toast.profileSaved': 'Profil Berhasil Disimpan',
    'toast.profileSavedDesc': 'Profil Anda telah diperbarui',
    'toast.profileSaveWarning': 'Profil diperbarui lokal',
    'toast.profileSaveWarningDesc': 'Perubahan mungkin tidak tersimpan di server',
    
    // Setup/Onboarding
    'setup.title': 'Setup Awal',
    'setup.subtitle': 'Mari mulai dengan data listrik Anda',
    'setup.step': 'Langkah',
    'setup.of': 'dari',
    'setup.next': 'Lanjut',
    'setup.back': 'Kembali',
    'setup.finish': 'Selesai',
    'setup.header.title': 'Mulai Perjalanan Hemat Energi Anda',
    'setup.header.subtitle': 'Kami hanya perlu beberapa informasi untuk membuat dashboard yang dipersonalisasi dan memberikan rekomendasi penghematan energi yang akurat',
    'setup.progress.profile': 'Profil Listrik',
    'setup.progress.devices': 'Perangkat',
    'setup.progress.done': 'Selesai',
    'setup.section1.title': 'Profil Listrik Anda',
    'setup.section1.subtitle': 'Informasi dasar tentang konsumsi energi Anda',
    'setup.section1.powerCategory': 'Golongan Daya (VA)',
    'setup.section1.powerCategory.hint': 'Pilih golongan daya PLN Anda',
    'setup.section1.selectedCapacity': 'Golongan Daya',
    'setup.section1.selectedPrice': 'Tarif per kWh',
    'setup.section1.kwhPrice': 'Tarif per kWh (Rp)',
    'setup.section1.kwhPrice.hint': 'Tarif PLN Anda',
    'setup.section1.monthlyBill': 'Tagihan Bulanan (Rp)',
    'setup.section1.monthlyBill.hint': 'Rata-rata per bulan',
    'setup.section2.title': 'Perangkat Elektronik Anda',
    'setup.section2.subtitle': 'Tambahkan perangkat yang sering Anda gunakan',
    'setup.device.title': 'Perangkat',
    'setup.device.name': 'Nama',
    'setup.device.watt': 'Watt',
    'setup.device.hours': 'Jam/Hari',
    'setup.device.consumption': 'Konsumsi',
    'setup.device.placeholder.name': 'Perangkat Baru',
    'setup.device.placeholder.watt': '500',
    'setup.device.placeholder.hours': '8',
    'setup.addDevice': 'Tambah Perangkat Lainnya',
    'setup.submit': 'Simpan ke Dashboard',
    'setup.secure': 'Data Anda aman dan terenkripsi',
    'setup.step1.title': 'Informasi Rumah',
    'setup.step1.subtitle': 'Berapa luas rumah atau kantor Anda?',
    'setup.step1.area': 'Luas Area (m²)',
    'setup.step1.placeholder': 'Contoh: 120',
    'setup.step1.tip': 'Tip',
    'setup.step1.tipText': 'Luas rumah standar di Indonesia berkisar 80-150 m²',
    'setup.step2.title': 'Tagihan Listrik',
    'setup.step2.subtitle': 'Berapa rata-rata tagihan bulanan Anda?',
    'setup.step2.bill': 'Tagihan Bulanan (Rp)',
    'setup.step2.placeholder': 'Contoh: 500000',
    'setup.step2.tip': 'Tip',
    'setup.step2.tipText': 'Lihat tagihan listrik PLN Anda bulan lalu',
    'setup.step3.title': 'Perangkat Listrik',
    'setup.step3.subtitle': 'Perangkat apa saja yang Anda miliki?',
    'setup.step3.placeholder': 'Pilih perangkat...',
    'setup.step3.addDevice': 'Tambah Perangkat',
    'setup.step3.remove': 'Hapus',
    'setup.step3.tip': 'Tip',
    'setup.step3.tipText': 'Tambahkan perangkat yang paling sering digunakan untuk analisis yang lebih akurat',
    'setup.step3.ac': 'AC (Air Conditioner)',
    'setup.step3.fridge': 'Kulkas',
    'setup.step3.washingMachine': 'Mesin Cuci',
    'setup.step3.tv': 'TV',
    'setup.step3.waterHeater': 'Pemanas Air',
    'setup.step3.rice': 'Rice Cooker',
    'setup.step3.fan': 'Kipas Angin',
    'setup.step3.lights': 'Lampu LED',
    'setup.step3.computer': 'Komputer',
    'setup.step3.microwave': 'Microwave',
    
    // Dashboard
    'dashboard.welcome': 'Halo, {name}!',
    'dashboard.title': 'Dasbor Analisis Energi',
    'dashboard.subtitle': 'Pantau konsumsi listrik Anda secara real-time',
    'dashboard.editProfile': 'Edit Profil',
    'dashboard.completeProfile': 'Lengkapi Profil',
    'dashboard.totalKwhUsage': 'Total Penggunaan kWh',
    'dashboard.thisMonth': 'Bulan ini',
    'dashboard.billEstimate': 'Estimasi Tagihan Akhir Bulan',
    'dashboard.fromLastMonth': 'dari bulan lalu',
    'dashboard.breakdown': 'Breakdown Biaya per Perangkat',
    'dashboard.breakdownDesc': 'Distribusi konsumsi energi bulanan',
    'dashboard.carbonFootprint': 'Carbon Footprint',
    'dashboard.co2Generated': 'CO₂ Dihasilkan bulan ini',
    'dashboard.totalDevices': 'Total Perangkat',
    'dashboard.connectedDevices': 'Perangkat Terhubung',
    'dashboard.anomalyDetected': 'Anomali Terdeteksi',
    'dashboard.anomalyDesc': 'Peningkatan konsumsi sebesar {percent} sejak {days} hari lalu. Kami menemukan beberapa perangkat yang menggunakan daya lebih tinggi dari biasanya.',
    'dashboard.viewRecommendations': 'Lihat Rekomendasi',
    'dashboard.dailyConsumption': 'Konsumsi Harian',
    'dashboard.last7Days': '7 hari terakhir (kWh)',
    'dashboard.target': 'Target',
    'dashboard.average': 'Rata-rata',
    'dashboard.peakHours': 'Waktu Puncak Konsumsi',
    'dashboard.consumptionPer3Hours': 'Konsumsi per 3 jam (kWh)',
    'dashboard.peak': 'Puncak',
    'dashboard.highest': 'tertinggi',
    'dashboard.consumption': 'Konsumsi',
    'dashboard.hour': 'Jam',
    'dashboard.device.ac': 'AC',
    'dashboard.device.fridge': 'Kulkas',
    'dashboard.device.lights': 'Lampu',
    'dashboard.device.others': 'Lainnya',
    'dashboard.day.mon': 'Sen',
    'dashboard.day.tue': 'Sel',
    'dashboard.day.wed': 'Rab',
    'dashboard.day.thu': 'Kam',
    'dashboard.day.fri': 'Jum',
    'dashboard.day.sat': 'Sab',
    'dashboard.day.sun': 'Min',
    
    // Recommendations
    'recommendations.title': 'Rekomendasi Hemat Energi',
    'recommendations.subtitle': 'Tindakan yang dipersonalisasi untuk mengurangi konsumsi energi dan biaya Anda',
    'recommendations.filter.all': 'Semua',
    'recommendations.filter.high': 'Prioritas Tinggi',
    'recommendations.filter.medium': 'Prioritas Sedang',
    'recommendations.filter.low': 'Prioritas Rendah',
    'recommendations.savings': 'Hemat',
    'recommendations.effort': 'Usaha',
    'recommendations.priority': 'Prioritas',
    'recommendations.high': 'Tinggi',
    'recommendations.medium': 'Sedang',
    'recommendations.low': 'Rendah',
    'recommendations.header.title': 'Langkah Cerdas: Hemat Rp {0} Bulan Ini',
    'recommendations.header.subtitle': 'Terapkan rekomendasi di bawah ini untuk mengoptimalkan konsumsi energi Anda',
    'recommendations.completed': '{0} dari {1} rekomendasi ditandai',
    'recommendations.potential': 'Potensi penghematan:',
    'recommendations.month': '/bulan',
    'recommendations.category.behavior': 'Perubahan Perilaku',
    'recommendations.category.upgrade': 'Peningkatan Perangkat',
    'recommendations.category.optimization': 'Optimasi Rutinitas',
    'recommendations.rec1.title': 'Coba naikkan suhu AC 1 derajat',
    'recommendations.rec1.desc': 'Menaikkan suhu AC dari 22°C ke 23°C dapat menghemat hingga 10% konsumsi energi tanpa mengurangi nyamanan secara signifikan.',
    'recommendations.rec2.title': 'Ganti pendingin ruangan lama dengan model inverter',
    'recommendations.rec2.desc': 'Pendingin ruangan dengan teknologi inverter menggunakan 30-40% energi lebih sedikit dibandingkan model konvensional. Investasi awal akan mengembalikan diri dalam 2-3 tahun.',
    'recommendations.rec3.title': 'Ganti lampu luar dengan sensor gerakan',
    'recommendations.rec3.desc': 'Sensor gerakan memastikan lampu hanya menyala ketika diperlukan, mengurangi waktu operasi hingga 70% dan menghemat energi secara signifikan.',
    'recommendations.difficulty': 'Tingkat Kesulitan:',
    'recommendations.easy': 'Mudah',
    'recommendations.moderate': 'Sedang',
    'recommendations.hard': 'Sulit',
    'recommendations.cta.title': 'Siap untuk mulai menghemat?',
    'recommendations.cta.subtitle': 'Tandai semua rekomendasi untuk melacak kemajuan Anda',
    'recommendations.cta.button': 'Terapkan Semua Suggestion Ini',
    'recommendations.cta.button.short': 'Terapkan Semua',
    'recommendations.savings.label': 'Potensi Penghematan',
    
    // Recommendation categories, titles, and descriptions
    'behavior_change': 'Perubahan Perilaku',
    'upgrade_device': 'Peningkatan Perangkat',
    'optimize_habits': 'Optimasi Rutinitas',
    'increase_ac_temp': 'Coba naikkan suhu AC 1 derajat',
    'increase_ac_temp_desc': 'Menaikkan suhu AC dari 22°C ke 23°C dapat menghemat hingga 10% konsumsi energi tanpa mengurangi nyamanan secara signifikan.',
    'replace_refrigerator': 'Ganti pendingin ruangan lama dengan model inverter',
    'replace_refrigerator_desc': 'Pendingin ruangan dengan teknologi inverter menggunakan 30-40% energi lebih sedikit dibandingkan model konvensional. Investasi awal akan mengembalikan diri dalam 2-3 tahun.',
    'use_motion_sensor': 'Ganti lampu luar dengan sensor gerakan',
    'use_motion_sensor_desc': 'Sensor gerakan memastikan lampu hanya menyala ketika diperlukan, mengurangi waktu operasi hingga 70% dan menghemat energi secara signifikan.',
    'easy': 'Mudah',
    'medium': 'Sedang',
    'hard': 'Sulit',
    
    // Sidebar
    'sidebar.dashboard': 'Dasbor',
    'sidebar.setup': 'Pengaturan',
    'sidebar.recommendations': 'Rekomendasi',
    'sidebar.reports': 'Laporan',
    'sidebar.devices': 'Perangkat',
    'sidebar.settings': 'Pengaturan',
    'sidebar.profile': 'Profile',
    'sidebar.reset': 'Reset Data',
    'sidebar.resetData': 'Reset Data',
    'sidebar.logout': 'Logout',
    'sidebar.loggedInAs': 'Logged in as',
    'sidebar.copyright': '© 2025 Voltura - Platform Energi Berkelanjutan Indonesia',
    'sidebar.tagline': 'Hemat Energi, Hemat Biaya, Selamatkan Bumi 🌱',
    'sidebar.resetDialog.title': 'Reset Electricity Data?',
    'sidebar.resetDialog.description': 'All your electricity data and devices will be deleted. You will return to the initial setup. This action cannot be undone.',
    'sidebar.resetDialog.cancel': 'Cancel',
    'sidebar.resetDialog.confirm': 'Yes, Reset',
    'sidebar.logoutDialog.title': 'Logout from Account?',
    'sidebar.logoutDialog.description': 'Are you sure you want to logout? You will need to login again to access the dashboard.',
    'sidebar.logoutDialog.cancel': 'Cancel',
    'sidebar.logoutDialog.confirm': 'Logout',
  },
  en: {
    // Common
    'common.voltura': 'Voltura',
    'common.slogan': 'See the Savings',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.logout': 'Logout',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.continue': 'Continue',
    
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Log in to your account to continue',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgot': 'Forgot password?',
    'login.button': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.signupLink': 'Sign Up Now',
    'login.hero.title': 'Manage Energy,\nSave the Planet',
    'login.hero.subtitle': 'Smart energy management platform for sustainable businesses in Indonesia',
    'login.feature1.title': 'Save up to 30%',
    'login.feature1.desc': 'Reduce electricity costs with AI-powered recommendations',
    'login.feature2.title': 'Real-time Monitoring',
    'login.feature2.desc': 'Track energy consumption live and accurately',
    'login.feature3.title': 'Environmental Impact',
    'login.feature3.desc': 'Track your contribution to carbon emission reduction',
    'login.error.fill': 'Please fill in all fields',
    'login.error.email': 'Invalid email format',
    'login.placeholder.email': 'name@company.com',
    'login.placeholder.password': 'Enter your password',
    'login.footer': '© 2025 Voltura - Sustainable Energy Platform Indonesia',
    
    // Signup
    'signup.title': 'Create New Account',
    'signup.subtitle': 'Sign up to start optimizing your energy',
    'signup.name': 'Full Name',
    'signup.email': 'Email',
    'signup.company': 'Company Name',
    'signup.phone': 'Phone Number',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.button': 'Create Account',
    'signup.loading': 'Creating account...',
    'signup.hasAccount': 'Already have an account?',
    'signup.loginLink': 'Login',
    'signup.hero.title': 'Manage Energy,\\nSave the Planet',
    'signup.hero.subtitle': 'Join thousands of businesses that have saved up to 30% on energy costs',
    'signup.benefit1.title': 'Save Electricity Costs',
    'signup.benefit1.desc': 'Identify energy wastage and get recommendations that can save up to 30%',
    'signup.benefit2.title': 'Real-time Monitoring',
    'signup.benefit2.desc': 'Monitor energy consumption directly from an easy-to-understand dashboard',
    'signup.benefit3.title': 'Quick Setup',
    'signup.benefit3.desc': 'Start in minutes with guided setup wizard',
    'signup.stats.users': 'Active Users',
    'signup.stats.savings': 'Average Savings',
    'signup.stats.co2': 'CO₂ Reduced',
    'signup.error.fill': 'Please fill in all fields',
    'signup.error.email': 'Invalid email format',
    'signup.error.password': 'Password must be at least 6 characters',
    'signup.error.match': 'Passwords do not match',
    'signup.placeholder.name': 'John Doe',
    'signup.placeholder.email': 'name@company.com',
    'signup.placeholder.company': 'PT. Example Indonesia',
    'signup.placeholder.phone': '08123456789',
    'signup.placeholder.password': 'Minimum 6 characters',
    'signup.placeholder.confirmPassword': 'Repeat password',
    
    // Toast notifications
    'toast.welcome': 'Welcome {{name}}!',
    'toast.accountCreated': 'Your account has been created successfully.',
    'toast.emailExists': 'Email already registered',
    'toast.emailExistsDesc': 'This email is already in use. Try logging in or use a different email.',
    'toast.goToLogin': 'Go to Login',
    'toast.signupFailed': 'Signup Failed',
    'toast.connectionError': 'Connection Error',
    'toast.networkError': 'Network error. Please check your connection and try again.',
    'toast.welcomeBack': 'Welcome back!',
    'toast.loggedInAs': 'Logged in as {{name}}',
    'toast.loginFailed': 'Login Failed',
    'toast.dataSaved': 'Data Berhasil Disimpan',
    'toast.dataSavedDesc': 'Setup listrik Anda telah tersimpan',
    'toast.dataSaveWarning': 'Setup selesai tapi tidak tersimpan',
    'toast.dataSaveWarningDesc': 'Anda tetap bisa melanjutkan menggunakan aplikasi',
    'toast.profileSaved': 'Profil Berhasil Disimpan',
    'toast.profileSavedDesc': 'Profil Anda telah diperbarui',
    'toast.profileSaveWarning': 'Profil diperbarui lokal',
    'toast.profileSaveWarningDesc': 'Perubahan mungkin tidak tersimpan di server',
    
    // Setup/Onboarding
    'setup.title': 'Initial Setup',
    'setup.subtitle': 'Let\'s start with your electricity data',
    'setup.step': 'Step',
    'setup.of': 'of',
    'setup.next': 'Next',
    'setup.back': 'Back',
    'setup.finish': 'Finish',
    'setup.header.title': 'Start Your Energy Saving Journey',
    'setup.header.subtitle': 'We just need a few pieces of information to create a personalized dashboard and provide accurate energy-saving recommendations',
    'setup.progress.profile': 'Electricity Profile',
    'setup.progress.devices': 'Devices',
    'setup.progress.done': 'Done',
    'setup.section1.title': 'Your Electricity Profile',
    'setup.section1.subtitle': 'Basic information about your energy consumption',
    'setup.section1.powerCategory': 'Power Category (VA)',
    'setup.section1.powerCategory.hint': 'Select your PLN power category',
    'setup.section1.selectedCapacity': 'Power Category',
    'setup.section1.selectedPrice': 'Price per kWh',
    'setup.section1.kwhPrice': 'Price per kWh (Rp)',
    'setup.section1.kwhPrice.hint': 'Your PLN tariff',
    'setup.section1.monthlyBill': 'Monthly Bill (Rp)',
    'setup.section1.monthlyBill.hint': 'Average per month',
    'setup.section2.title': 'Your Electronic Devices',
    'setup.section2.subtitle': 'Add devices you frequently use',
    'setup.device.title': 'Device',
    'setup.device.name': 'Name',
    'setup.device.watt': 'Watt',
    'setup.device.hours': 'Hours/Day',
    'setup.device.consumption': 'Consumption',
    'setup.device.placeholder.name': 'New Device',
    'setup.device.placeholder.watt': '500',
    'setup.device.placeholder.hours': '8',
    'setup.addDevice': 'Add Another Device',
    'setup.submit': 'Save to Dashboard',
    'setup.secure': 'Your data is safe and encrypted',
    'setup.step1.title': 'Home Information',
    'setup.step1.subtitle': 'How large is your home or office?',
    'setup.step1.area': 'Area Size (m²)',
    'setup.step1.placeholder': 'Example: 120',
    'setup.step1.tip': 'Tip',
    'setup.step1.tipText': 'Standard home size in Indonesia ranges from 80-150 m²',
    'setup.step2.title': 'Electricity Bill',
    'setup.step2.subtitle': 'What is your average monthly bill?',
    'setup.step2.bill': 'Monthly Bill (Rp)',
    'setup.step2.placeholder': 'Example: 500000',
    'setup.step2.tip': 'Tip',
    'setup.step2.tipText': 'Check your last month\'s PLN electricity bill',
    'setup.step3.title': 'Electric Devices',
    'setup.step3.subtitle': 'What devices do you have?',
    'setup.step3.placeholder': 'Select device...',
    'setup.step3.addDevice': 'Add Device',
    'setup.step3.remove': 'Remove',
    'setup.step3.tip': 'Tip',
    'setup.step3.tipText': 'Add devices you use most frequently for more accurate analysis',
    'setup.step3.ac': 'AC (Air Conditioner)',
    'setup.step3.fridge': 'Refrigerator',
    'setup.step3.washingMachine': 'Washing Machine',
    'setup.step3.tv': 'TV',
    'setup.step3.waterHeater': 'Water Heater',
    'setup.step3.rice': 'Rice Cooker',
    'setup.step3.fan': 'Fan',
    'setup.step3.lights': 'LED Lights',
    'setup.step3.computer': 'Computer',
    'setup.step3.microwave': 'Microwave',
    
    // Dashboard
    'dashboard.welcome': 'Hello, {name}!',
    'dashboard.title': 'Energy Analysis Dashboard',
    'dashboard.subtitle': 'Monitor your electricity consumption in real-time',
    'dashboard.editProfile': 'Edit Profile',
    'dashboard.completeProfile': 'Complete Profile',
    'dashboard.totalKwhUsage': 'Total kWh Usage',
    'dashboard.thisMonth': 'This Month',
    'dashboard.billEstimate': 'End of Month Bill Estimate',
    'dashboard.fromLastMonth': 'from last month',
    'dashboard.breakdown': 'Cost Breakdown per Device',
    'dashboard.breakdownDesc': 'Monthly energy consumption distribution',
    'dashboard.carbonFootprint': 'Carbon Footprint',
    'dashboard.co2Generated': 'CO₂ Generated this month',
    'dashboard.totalDevices': 'Total Devices',
    'dashboard.connectedDevices': 'Connected Devices',
    'dashboard.anomalyDetected': 'Anomaly Detected',
    'dashboard.anomalyDesc': 'Consumption increased by {percent} since {days} days ago. We found some devices using more power than usual.',
    'dashboard.viewRecommendations': 'View Recommendations',
    'dashboard.dailyConsumption': 'Daily Consumption',
    'dashboard.last7Days': 'Last 7 days (kWh)',
    'dashboard.target': 'Target',
    'dashboard.average': 'Average',
    'dashboard.peakHours': 'Peak Consumption Time',
    'dashboard.consumptionPer3Hours': 'Consumption per 3 hours (kWh)',
    'dashboard.peak': 'Peak',
    'dashboard.highest': 'highest',
    'dashboard.consumption': 'Consumption',
    'dashboard.hour': 'Hour',
    'dashboard.device.ac': 'AC',
    'dashboard.device.fridge': 'Refrigerator',
    'dashboard.device.lights': 'Lights',
    'dashboard.device.others': 'Others',
    'dashboard.day.mon': 'Mon',
    'dashboard.day.tue': 'Tue',
    'dashboard.day.wed': 'Wed',
    'dashboard.day.thu': 'Thu',
    'dashboard.day.fri': 'Fri',
    'dashboard.day.sat': 'Sat',
    'dashboard.day.sun': 'Sun',
    
    // Recommendations
    'recommendations.title': 'Energy Saving Recommendations',
    'recommendations.subtitle': 'Personalized actions to reduce your energy consumption and costs',
    'recommendations.filter.all': 'All',
    'recommendations.filter.high': 'High Priority',
    'recommendations.filter.medium': 'Medium Priority',
    'recommendations.filter.low': 'Low Priority',
    'recommendations.savings': 'Savings',
    'recommendations.effort': 'Effort',
    'recommendations.priority': 'Priority',
    'recommendations.high': 'High',
    'recommendations.medium': 'Medium',
    'recommendations.low': 'Low',
    'recommendations.header.title': 'Smart Steps: Save Rp {0} This Month',
    'recommendations.header.subtitle': 'Apply the recommendations below to optimize your energy consumption',
    'recommendations.completed': '{0} of {1} recommendations marked',
    'recommendations.potential': 'Potential savings:',
    'recommendations.month': '/month',
    'recommendations.category.behavior': 'Behavior Change',
    'recommendations.category.upgrade': 'Device Upgrade',
    'recommendations.category.optimization': 'Habit Optimization',
    'recommendations.rec1.title': 'Try raising AC temperature 1 degree',
    'recommendations.rec1.desc': 'Raising AC temperature from 22°C to 23°C can save up to 10% energy consumption without significantly reducing comfort.',
    'recommendations.rec2.title': 'Replace old refrigerator with Inverter model',
    'recommendations.rec2.desc': 'Refrigerators with inverter technology use 30-40% less energy than conventional models. Initial investment will return in 2-3 years.',
    'recommendations.rec3.title': 'Replace outdoor lights with motion sensors',
    'recommendations.rec3.desc': 'Motion sensors ensure lights only turn on when needed, reducing operating time by up to 70% and significantly saving energy.',
    'recommendations.difficulty': 'Difficulty Level:',
    'recommendations.easy': 'Easy',
    'recommendations.moderate': 'Moderate',
    'recommendations.hard': 'Hard',
    'recommendations.cta.title': 'Ready to start saving?',
    'recommendations.cta.subtitle': 'Mark all recommendations to track your progress',
    'recommendations.cta.button': 'Apply All These Suggestions',
    'recommendations.cta.button.short': 'Apply All',
    'recommendations.savings.label': 'Potential Savings',
    
    // Recommendation categories, titles, and descriptions
    'behavior_change': 'Behavior Change',
    'upgrade_device': 'Device Upgrade',
    'optimize_habits': 'Habit Optimization',
    'increase_ac_temp': 'Try raising AC temperature 1 degree',
    'increase_ac_temp_desc': 'Raising AC temperature from 22°C to 23°C can save up to 10% energy consumption without significantly reducing comfort.',
    'replace_refrigerator': 'Replace old refrigerator with Inverter model',
    'replace_refrigerator_desc': 'Refrigerators with inverter technology use 30-40% less energy than conventional models. Initial investment will return in 2-3 years.',
    'use_motion_sensor': 'Replace outdoor lights with motion sensors',
    'use_motion_sensor_desc': 'Motion sensors ensure lights only turn on when needed, reducing operating time by up to 70% and significantly saving energy.',
    'easy': 'Easy',
    'medium': 'Moderate',
    'hard': 'Hard',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.setup': 'Setup',
    'sidebar.recommendations': 'Recommendations',
    'sidebar.reports': 'Reports',
    'sidebar.devices': 'Devices',
    'sidebar.settings': 'Settings',
    'sidebar.profile': 'Profile',
    'sidebar.reset': 'Reset Data',
    'sidebar.resetData': 'Reset Data',
    'sidebar.logout': 'Logout',
    'sidebar.loggedInAs': 'Logged in as',
    'sidebar.copyright': '© 2025 Voltura - Indonesia Sustainable Energy Platform',
    'sidebar.tagline': 'Save Energy, Save Money, Save the Planet 🌱',
    'sidebar.resetDialog.title': 'Reset Electricity Data?',
    'sidebar.resetDialog.description': 'All your electricity data and devices will be deleted. You will return to the initial setup. This action cannot be undone.',
    'sidebar.resetDialog.cancel': 'Cancel',
    'sidebar.resetDialog.confirm': 'Yes, Reset',
    'sidebar.logoutDialog.title': 'Logout from Account?',
    'sidebar.logoutDialog.description': 'Are you sure you want to logout? You will need to login again to access the dashboard.',
    'sidebar.logoutDialog.cancel': 'Cancel',
    'sidebar.logoutDialog.confirm': 'Logout',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('id');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}